name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Build the project
        run: make

      - name: Run tests
        run: make test

      - name: Clean build files (optional)
        run: make clean