name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev

      - name: Build the project
        run: |
          make

      - name: Run tests
        run: |
          ./test_ascii85

      - name: Clean build files (optional)
        run: |
          make clean