name: Build & Test

on: 
  push:
    branches:
      - main
      - gaussian-method

  pull_request:
    branches:
      - main 
      - gaussian-method

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev cmake
          cd /usr/src/googletest && sudo cmake . && sudo make
          sudo cp /usr/src/googletest/lib/*.a /usr/lib
          ls /usr/include/gtest/gtest

      - name: Install Eigen 
        run: |
          sudo apt-get install -y libeigen3-dev

      - name: Build
        run: |
          make
        working-directory: gaussian-method

      - name: Run tests
        run: |
          make test
        working-directory: gaussian-method

      - name: Clean build files
        run: |
          make clean
        working-directory: gaussian-method
