name: Build & Test

on: 
  push:
    branches:
      - main
      
  pull_request:
    branches:
        - main
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev python3

          cd /usr/src/googletest && sudo cmake . && sudo make
          sudo cp /usr/src/googletest/lib/*.a /usr/lib

      - name: Build the ascii85
        run: |
          make

      - name: Run all tests for ascii85
        run: |
          make test


      - name: Clean build files for ascii85
        run: |
          make clean