name: Build & Test

on: 
  push:
    branches:
      - main
    paths:
      - 'ascii85/**'
      - 'gaussian-method/**'  
  pull_request:
    branches:
      - main
    paths:
      - 'ascii85/**'
      - 'gaussian-method/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and GoogleTest (for ascii85)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev python3

          cd /usr/src/googletest && sudo cmake . && sudo make
          sudo cp /usr/src/googletest/lib/*.a /usr/lib

      - name: Install Eigen (for gaussian-method)
        run: |
          sudo apt-get install -y libeigen3-dev

      - name: Build ascii85
        run: |
          cd ascii85 && make

      - name: Run tests for ascii85
        run: |
          cd ascii85 && make test

      - name: Clean ascii85 build files
        run: |
          cd ascii85 && make clean

      - name: Build gaussian-method
        run: |
          cd gaussian-method && make

      - name: Run tests for gaussian-method
        run: |
          cd gaussian-method && make test

      - name: Clean gaussian-method build files
        run: |
          cd gaussian-method && make clean
