name: Build & Test

on: 
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install Eigen 
        run: |
          sudo apt-get install -y libeigen3-dev

      
      - name: Build
        run: |
          make
        working-directory: gaussian-method

      - name: Run tests
        run: |
          make test
        working-directory: gaussian-method

      - name: Clean build files
        run: |
          make clean
        working-directory: gaussian-method  
